name: Auto Merge Feature to Release

on:
  push:
    branches:
      - 'feature_202512/*'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge to release
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mergeMethod: merge
          base: release
          head: ${{ github.ref_name }}